version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.3.1
    container_name: mlflow-server
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlruns/mlflow.db
      --default-artifact-root ./mlruns
      --host 0.0.0.0
      --port 5000
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000
