training:
  # Hyperparameters
  epochs: 15
  batch_size: 32
  learning_rate: 0.001
  image_size: 64
  num_classes: 2

  # Data
  bucket_name: objetos-random-tutoriales
  train_prefix: train
  val_prefix: val
  test_prefix: test

  # SageMaker
  instance_type: ml.p3.2xlarge # GPU instance
  instance_count: 1
  framework_version: "1.12.0"
  py_version: py38

  # Model versioning
  model_name: image-classifier
  experiment_name: cat-fish-classification
